name = "DPC"
uuid = "2cfc0b36-c815-11e8-3a47-49b3c0410e59"
authors = ["jleugeri <jleugeri@uos.de>", "pnieters <pnieters@uos.de>"]
version = "1.0.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
